services:
  - type: web
    name: my-backend
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "python3 app.py"
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.daojspoqqwlcrwlemrwo:WqfpPLAOWLyYBGtn@aws-0-us-east-1.pooler.supabase.com:6543/postgres
